from .computerName import getComputerName
from .domain import getDomain
from .osVersion import getOsVersion
from .platform import getArchitecture
from .username import getUsername
from .timezone import getDateTime
from .language import getLanguage
from .bios import getBios
from .directX import getDirectXVersion
from .softwares import getSoftwares